# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-06 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokecards', '0003_gamequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamequestion',
            name='game_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokecards.GameState'),
        ),
    ]
