# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-07 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokecards', '0004_gamequestion_game_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='game_questions',
            field=models.TextField(default='', verbose_name='A comma delimited list of the questions for this game instance'),
        ),
    ]
