# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-14 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Education degree, such as Doctor of Philosophy')),
                ('field', models.CharField(max_length=100, verbose_name='Name of the field, such as Mechanical Engineering')),
                ('date', models.CharField(max_length=100, verbose_name='Date of degree, shortened, such as May 2013')),
                ('school', models.CharField(max_length=100, verbose_name='The name of the university')),
                ('thesis', models.CharField(max_length=100, verbose_name='Title of thesis if a thesis was completed')),
                ('gpa', models.FloatField(verbose_name='The numeric GPA for this degree')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job title')),
                ('date', models.CharField(max_length=100, verbose_name='Descriptive time frame working for this company')),
                ('company', models.CharField(max_length=100, verbose_name='Company name')),
                ('description', models.TextField(verbose_name='A description of job responsibilities, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='An attribute of this membership')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name on resume')),
                ('email', models.EmailField(max_length=254, verbose_name='Email address of person')),
                ('github_id', models.CharField(max_length=30, verbose_name='GitHub ID of person')),
                ('goal', models.TextField(verbose_name='Purpose/goal of the person')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='An attribute of this project')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500, verbose_name='Pre-prettified list of authors')),
                ('year', models.IntegerField(verbose_name='Year of publication')),
                ('title', models.CharField(max_length=500, verbose_name='Title of publication')),
                ('container', models.CharField(max_length=500, verbose_name='Pre-prettified conference or journal information')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='A description of this skill')),
            ],
        ),
    ]
