# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.AddField(
            model_name='experience',
            name='json_description',
            field=models.TextField(null=True, verbose_name='A JSON string description of job responsibilities, etc.'),
        ),
    ]
